name: "Update protobufs"
on: workflow_dispatch

jobs:
  update-protobufs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update Submodule
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Download nanopb
        run: |
          wget https://jpa.kapsi.fi/nanopb/download/nanopb-0.4.6-linux-x86.tar.gz
          tar xvzf nanopb-0.4.6-linux-x86.tar.gz
          mv nanopb-0.4.6-linux-x86 nanopb-0.4.6

      - name: Re-generate protocol buffers
        run: |
          ./bin/regen-protobufs.sh

      - name: Commit update
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add protobufs
          git add meshtastic
          git commit -m "Update protobuf submodule" && git push || echo "No changes to commit"
